package ch.admin.bag.covidcertificate.backend.delivery.model.app;

import ch.ubique.openapi.docannotations.Documentation;
import javax.validation.constraints.NotNull;

public class DeliveryRegistration {
    @Documentation(
            description =
                    "client generated alpha numeric code used as identifier during the entire transfer")
    @NotNull
    private String code;

    @Documentation(description = "base64 encoded public key generated by client")
    @NotNull
    private String publicKey;

    @Documentation(description = "algorithm used to generate public key. 'RSA' or 'EC'")
    @NotNull
    private String alg;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getAlg() {
        return alg;
    }

    public void setAlg(String alg) {
        this.alg = alg;
    }
}
