package ch.admin.bag.covidcertificate.backend.delivery.model.app;

import ch.admin.bag.covidcertificate.backend.delivery.model.util.CodeHelper;
import ch.ubique.openapi.docannotations.Documentation;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class DeliveryRegistration {
    @Documentation(
            description =
                    "(DEPRECATED) client generated alpha numeric code used as identifier during the entire transfer",
            example = "A7KBZ91XL")
    @NotNull
    private String code;

    @Documentation(
            description = "base64 encoded public key generated by client",
            example =
                    "BIECvEpBWglf3LU/Bk9sybpPBorlknUF5j4QptPdAqDauKo0DWT+cZuRpx0hz2W3E9YeeNpcZ5LTfqpKsJcav+A=")
    @NotNull
    private String publicKey;

    @Documentation(
            description = "algorithm used for public key generation. EC256 or RSA2048",
            example = "EC256")
    @NotNull
    private Algorithm algorithm;

    @Documentation(
            description =
                    "payload which was signed with format ${action}:${code}:${unix_timestamp_in_ms}, where action is one of delete|get|register",
            example = "register:A7KBZ91XL:1623051081000")
    @NotNull
    private String signaturePayload;

    @Documentation(description = "the signature calculated over signaturePayload. base64 encoded")
    @NotNull
    private String signature;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = CodeHelper.getSanitizedCode(code);
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public Algorithm getAlgorithm() {
        return algorithm;
    }

    public void setAlgorithm(Algorithm algorithm) {
        this.algorithm = algorithm;
    }

    public String getSignaturePayload() {
        return signaturePayload;
    }

    public void setSignaturePayload(String signaturePayload) {
        this.signaturePayload = signaturePayload;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }
}
