### hello
GET {{baseUrl}}/app/delivery/v1
Accept: application/json

### register for delivery
POST {{baseUrl}}/app/delivery/v1/covidcert/register
Content-Type: application/json

{
  "code": "A7KBZ91XL",
  "publicKey": "base64string",
  "signature": "base64string",
  "signaturePayload": "register:A7KBZ91XL:1623051081000"
}

### register for push
POST {{baseUrl}}/app/delivery/v1/push/register
Content-Type: application/json

{
  "pushToken": "some_push_token",
  "pushType": "IOS"
}

### deregister for push
POST {{baseUrl}}/app/delivery/v1/push/deregister
Content-Type: application/json

{
  "pushToken": "some_push_token",
  "pushType": "IOS"
}

### request covidcert delivery
POST {{baseUrl}}/app/delivery/v1/covidcert
Content-Type: application/json

{
  "code": "A7KBZ91XL",
  "signature": "base64string",
  "signaturePayload": "get:A7KBZ91XL:1623051081000"
}

### delete covidcert
POST {{baseUrl}}/app/delivery/v1/covidcert/complete
Content-Type: application/json

{
  "code": "A7KBZ91XL",
  "signature": "base64string",
  "signaturePayload": "get:A7KBZ91XL:1623051081000"
}