### hello
GET {{baseUrl}}/v1/app
Accept: application/json

### register for delivery
POST {{baseUrl}}/v1/app/delivery/covidcert/register
Content-Type: application/json

{
  "code": "ABC-02-43-YH",
  "publicKey": "base64string",
  "signature": "base64string",
  "signaturePayload": "register:A7KBZ91XL:1623051081000"
}

### register for push
POST {{baseUrl}}/v1/app/delivery/push/register
Content-Type: application/json

{
  "pushToken": "some_push_token",
  "pushType": "IOS"
}

### deregister for push
POST {{baseUrl}}/v1/app/delivery/push/deregister
Content-Type: application/json

{
  "pushToken": "some_push_token",
  "pushType": "IOS"
}

### request covidcert delivery
POST {{baseUrl}}/v1/app/delivery/covidcert
Content-Type: application/json

{
  "code": "ABC-02-43-YH",
  "signature": "base64string",
  "signaturePayload": "get:A7KBZ91XL:1623051081000"
}

### delete covidcert
POST {{baseUrl}}/v1/app/delivery/covidcert/delete
Content-Type: application/json

{
  "code": "ABC-02-43-YH",
  "signature": "base64string",
  "signaturePayload": "get:A7KBZ91XL:1623051081000"
}