### hello
GET {{baseUrl}}/cgs/delivery/v1
Accept: application/json

### register for delivery
POST {{baseUrl}}/cgs/delivery/v1/delivery/covidcert
Content-Type: application/json

{
  "code": "ABC-02-43-YH",
  "hcert": "base64string",
  "pdf": "base64string"
}