### hello
GET {{baseUrl}}/cgs/delivery/v1
Accept: application/json

### deliver
POST {{baseUrl}}/cgs/delivery/v1/covidcert
Content-Type: application/json

{
  "code": "41CUS0TCH",
  "hcert": "base64string",
  "pdf": "base64string"
}